[package]
name = "psudoc"
version = "0.1.0"
authors = ["RanolP <public.ranolp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpsudoc = { path = "../libpsudoc" } 
colored = "1.8.0"
unicode-width = "0.1.5"
[dependencies.syntect]
version = "3.2.0"
features = ["parsing", "yaml-load"]
